"""Writes an evaluation as Markdown, for people, and JSON, for tools."""

import json
from dataclasses import asdict

from simulator.client import ALERTS
from simulator.evaluation import Evaluation

RULE_NAMES = {alert_type: name for alert_type, _, name in ALERTS}


def percent(value: float) -> str:
    return f"{value * 100:.0f}%"


def seconds(value: float | None) -> str:
    if value is None:
        return "—"
    if value < 10:
        return f"{value:.1f} s"
    if value < 60:
        return f"{value:.0f} s"
    return f"{value / 60:.1f} min"


def milliseconds(value: float | None) -> str:
    return "—" if value is None else f"{value:.0f} ms"


def number(value: float | None) -> str:
    return "—" if value is None else f"{value:g}"


def to_json(evaluation: Evaluation) -> str:
    return json.dumps(asdict(evaluation), indent=2) + "\n"


def to_markdown(evaluation: Evaluation) -> str:
    e = evaluation
    attempts = e.routine_sign_ins + e.routine_failures
    lines = [
        "# Detection evaluation",
        "",
        f"Generated by `python -m simulator` (seed {e.seed}) on "
        f"{e.started_at[:10]}, in {e.duration_seconds:.0f} seconds. The method "
        "is described in `backend/README.md` (Attack simulator).",
        "",
        "## Summary",
        "",
        *(
            [
                "> **Not a fresh database.** It held alerts from before this run. "
                "Password spray and brute force count from their latest alert "
                "for an address or email, so earlier runs change their results.",
                "",
            ]
            if e.earlier_alerts
            else []
        ),
        f"- **Attacks detected:** {e.detected} of {e.attacks} "
        f"({percent(e.detection_rate)})",
        f"- **Evasive variants detected:** {e.evasive_detected} of "
        f"{e.evasive_attacks} (see Evasion)",
        f"- **False positives:** {len(e.false_positives)} over {attempts} "
        f"routine sign-in attempts by {e.people} people "
        f"({e.false_positives_per_1000_sign_ins:.1f} per 1,000)",
        f"- **Precision:** {percent(e.precision)} of {e.alerts} alerts point "
        "at an attack",
        f"- **Routine ingestion:** {attempts} sign-ins in "
        f"{e.routine_ingest_ms / 1000:.1f} s, detection included",
        "",
        "## By rule",
        "",
        "| Rule | Technique | Detected | Steps to detect (median) "
        "| Attack time to detect (median / max) | Pipeline latency (median / max) "
        "| False positives |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for rule in e.rules:
        lines.append(
            f"| {RULE_NAMES[rule.alert_type]} | {rule.technique} "
            f"| {rule.detected}/{rule.attacks} ({percent(rule.detection_rate)}) "
            f"| {number(rule.median_steps_to_detect)} "
            f"| {seconds(rule.median_seconds_to_detect)} / "
            f"{seconds(rule.max_seconds_to_detect)} "
            f"| {milliseconds(rule.median_latency_ms)} / "
            f"{milliseconds(rule.max_latency_ms)} "
            f"| {rule.false_positives} |"
        )

    lines += [
        "",
        "## Evasion",
        "",
        "Variants built to pass under one rule, the way a careful attacker "
        "would. Any alert that names them counts as catching them, whichever "
        "rule raised it. A variant that passes marks a limit of the rules, "
        "not a failure of the run.",
        "",
        "| Variant | Technique | Passes under | Why | Detected | Caught by |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for evasion in e.evasions:
        caught_by = ", ".join(f"`{alert}`" for alert in evasion.caught_by) or "—"
        lines.append(
            f"| `{evasion.variant}` | {evasion.technique} "
            f"| {RULE_NAMES[evasion.evades]} | {evasion.evasion} "
            f"| {evasion.detected}/{evasion.attacks} | {caught_by} |"
        )
    lines += [
        "",
        "## Benign behaviour",
        "",
        "Things real people do that a rule could take for an attack. The "
        "expected alert follows from each rule's design; a case marked as "
        "expected to alert is a known limit, not a surprise.",
        "",
        "| Case | What happens | Expected | Alerts raised | As expected |",
        "| --- | --- | --- | --- | --- |",
    ]
    for case in e.cases:
        raised = ", ".join(f"`{alert}`" for alert in case.alerts) or "none"
        expected = f"`{case.expected_alert}`" if case.expected_alert else "none"
        lines.append(
            f"| `{case.name}` | {case.description} | {expected} | {raised} "
            f"| {'yes' if case.as_expected else '**no**'} |"
        )

    lines += ["", "## False positives", ""]
    if e.false_positives:
        lines += [
            "| Alert | Technique | Cause | Message |",
            "| --- | --- | --- | --- |",
        ]
        lines += [
            f"| `{fp.alert_type}` | {fp.technique} | `{fp.cause}` | {fp.message} |"
            for fp in e.false_positives
        ]
    else:
        lines.append("None.")

    lines += [
        "",
        "## Attacks",
        "",
        "Evasive variants are marked *(evasive)*.",
        "",
        "| Attack | Technique | What it does | Detected | Steps to detect "
        "| Attack time to detect | Pipeline latency |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for d in e.detections:
        steps = f"{d.steps_to_detect} of {d.steps}" if d.detected else f"— of {d.steps}"
        name = f"{d.attack} *(evasive)*" if d.evasion else d.attack
        lines.append(
            f"| {name} | {d.technique} | {d.description} "
            f"| {'yes' if d.detected else '**no**'} | {steps} "
            f"| {seconds(d.seconds_to_detect)} | {milliseconds(d.latency_ms)} |"
        )
    lines += [
        "",
        "## Scope",
        "",
        "- The evasive variants are the ones this project chose; a real attacker "
        "has more. Slow brute force is not among them: its lockout counts only "
        "this application's own sign-ins, in real time, so it cannot be "
        "replayed in seconds.",
        "- Five attacks per rule and per variant against one synthetic "
        "organization: the rates "
        "describe this scenario, not real attacks in general.",
        "- The seed fixes the people, devices and behaviour; the calendar follows "
        "the day of the run, so counts can differ slightly from one day to the next.",
    ]
    return "\n".join(lines) + "\n"
